version: 2
formats: []

build:
  image: latest

sphinx:
  builder: html
  configuration: docs/src/conf.py
  fail_on_warning: true

python:
  version: 3.7
  install: 
    - method: pip
    - requirements: docs/requirements.txt
    path: .
    extra_requirements:
      - docs